### ISSUE TITLE
Add inline scope for a single line after a parenthesized expression

### ISSUE THREAD

**Issue by Kirdow** [Kirdow/Dern#5]
When doing either an if statement, while loop (requires #2) or other branching/scope based operations, if only a single line is needed, omitting the curly braces should be possible as seen in the following 2 examples.

1\)
```dern
var age = 15;
write("Hello,");
if (age >= 18)
    write(" Adult");
print(" World!");
```
2\)
```dern
func incCount() -> $number {
    var result = counter;
    counter = counter + 1;
    return result;
}

var counter = 1;
while (incCount() < 15)
    print(counter + "% 5 = " + (counter % 5));
```

# Tasks for Inline Scope
- [ ] If statement working
- [ ] While loop working (requires #2)
- [ ] Still use its own scope
- [ ] Not allow `var` keyword as it's redundant
- [ ] Support omitting scope by directly using a semicolon
