### ISSUE TITLE
Add input keyword for command line input

### ISSUE THREAD

**Issue by Kirdow** [Kirdow/Dern#6]
Input should not require any preceding text but should still be a possible parameter.
The keyword would be `read` and would look like in these examples.
1\)
```dern
var name = read("What is your name? ");
print("Hello, " + name);
```
2\)
```dern
var age = read("What is your age? ");
if (age >= 18) {
    print("You are an adult!");
} else {
    print("You are not an adult!");
}
```
3\)
```dern
write("Write any sentence: ");
var sentence = read();
print("Your sentence:\n" + sentence);
```

As seen in example 1, `read` can take a preceding text and will read a text.
As seen in example 2, `read` can also parse numbers successfully if the format matches. This will currently cause an issue if the user enter a text, a fix will be implemented in the future.
As seen in example 3, `read` can omit the preceding text, but you can still use it using `write` on the line before.

# Tasks for Input Keyword
- [x] Support no parameter
- [x] Support parameter for preceding text
- [x] Return number if recognized as a number
- [x] Return text if not recognized as a number

**Comment by Kirdow** [comment]
Currently doesn't support no parameter until #8 is fixed.
Example 2 is also failing for numbers above (or equal to) 18 because of #9.

**Comment by Kirdow** [comment]
All 3 examples now work and all tasks are completed as of 5319dbb.
